import Head from "next/head";

// t3- https://www.youtube.com/watch?v=J1gzN1SAhyM
// embeddings and chatbot- https://www.youtube.com/watch?v=RM-v7zoYQo0

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <div>
        <h1>Chatify</h1>
        <p>you can now chat with your documents on the go!</p>
      </div>
    </>
  );
}
